### ISSUE TITLE
Проверка возможности нанесения удара

### ISSUE THREAD

**Issue by madddmax** [hippogamesunity/RussianAICup2017#2]
https://github.com/hippogamesunity/RussianAICup2017/blob/5727fa81abdcb0c58d8d709f7a9e190e939355e3/csharp-cgdk/NuclearStrike.cs#L12

Дополнительно нужно условие возможности нанесения удара: me.RemainingNuclearStrikeCooldownTicks == 0

**Comment by hippogamesunity** [comment]
Такие вещи можешь сам смело править, раз это баг, ты его нашел и исправление тривиальное)

**Comment by hippogamesunity** [comment]
if (Global.Me.NextNuclearStrikeTickIndex == -1 && Global.Me.RemainingNuclearStrikeCooldownTicks == 0 && Global.World.TickIndex % 30 == 0)
